name: "linear-app-create-issue"
description: "GitHub Action to create an Issue for Linear.app."

branding:
  icon: check-square
  color: purple
author: "James Acklin <james@ackl.in>"

inputs:
  issueTitle:
    required: true
    description: "Issue title from GH event"
  issueContent:
    required: true
    description: "Issue markdown from GH event"
  apiKey:
    required: true
    description: "API key from Linear.app"
  teamId:
    required: true
    description: "Team ID from Linear.app"
  stateId:
    required: true
    description: "State ID from Linear.app"

runs:
  using: "node16"
  main: "dist/index.js"
